name: Deploy to Astro to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up Node.js with pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build Astro with pnpm
        run: pnpm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
